# Generated by Django 5.1.2 on 2025-01-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0002_alter_subscription_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="live_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="stripe_product_id",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="type",
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
