# Generated by Django 5.1.2 on 2025-01-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0003_subscriptionplan_live_mode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="stripe_customer_id",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="stripe_subscription_id",
            field=models.TextField(unique=True),
        ),
    ]
