# Generated by Django 5.1.2 on 2025-01-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0004_alter_subscription_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="stripe_status",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="stripe_customer_id",
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="stripe_subscription_id",
            field=models.TextField(db_index=True),
        ),
    ]
