# Generated by Django 5.0.6 on 2024-07-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_uploadedfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="membership",
            field=models.CharField(
                choices=[
                    ("Free-Trial", "Free-Trial"),
                    ("Monthly", "Monthly"),
                    ("Annually", "Annually"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
