# Generated by Django 5.0.6 on 2024-08-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_account_membership"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
    ]
