# Generated by Django 5.0.6 on 2024-08-06 08:49

from django.db import migrations, models

import accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_account_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="membership_expiration_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="membership_status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Expired", "Expired")],
                default="",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="profile_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=accounts.models.user_profile_photo_path
            ),
        ),
    ]
