# Generated by Django 5.1.2 on 2025-01-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_account_id_alter_uploadedfile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="phone_number",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
