# Generated by Django 5.1.2 on 2025-01-15 09:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_alter_account_membership_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="membership",
        ),
        migrations.RemoveField(
            model_name="account",
            name="membership_expiration_date",
        ),
        migrations.RemoveField(
            model_name="account",
            name="membership_status",
        ),
    ]
