name: 'On pull request'
on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/on-pull.yml
      - app/**
      - Dockerfile
      - poetry.lock
      - pyproject.toml

  push:
    branches:
      - main
    paths:
      # - .github/workflows/on-pull.yml
      - app/**
      - Dockerfile
      - poetry.lock
      - pyproject.toml

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  run-test:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: "python-skeleton-template"
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 'Check Python linting'
        uses: chartboost/ruff-action@v1
        id: ruff-check
        with:
          version: 0.4.3
          src: './app'
          args: 'check --fix'

      - name: Azure login
        uses: azure/login@v2.2.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build & push the image to ACR
        uses: azure/CLI@v2.1.0
        with:
          azcliversion: latest
          inlineScript: |
            az acr build -r ${REGISTRY_NAME} -g ${RESOURCE_GROUP} -t ${IMAGE_NAME}:latest .
        env:
          REGISTRY_NAME: csatanalysisacr
          RESOURCE_GROUP: django-app
          IMAGE_NAME: csat-streamlit-app
